### ISSUE TITLE
Exercise numbering like DatKom and BuS

### ISSUE THREAD

**Issue by lgoettgens** [ninov/solution-tex#3]
Pls add funktionality for the DatKom and BuS style of exercise numbering "sheetNumber.exerciseNumber", e.g. "3.1" for the first exercise on sheet three

**Comment by ninavdl** [comment]
I thought about that - something like `\setexercisestyle{…}`?

Meanwhile, something like
```latex
\titleformat{\section}
	{\normalfont\Large\bfseries}
	{\lExercise \sheetnum.\thesection}
	{1em}
	{\normalfont}
``` 
should to the trick.
